# Workflow to access AWS resources when the workflow is linked to a branch
name: Déploiement sur EC2 AWS
on:
  push:
    branches:
      - master
env:
  AWS_REGION : eu-west-1
  AWS_EC2 : ec2-34-254-161-117.eu-west-1.compute.amazonaws.com
  GITHUB_REPO : https://github.com/RR-DataSciences/P7_Implement_a_scoring_model
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  MajPullOnEC2:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          path: P7_Implement_a_scoring_model
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::010526279977:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ env.AWS_EC2 }} >> ~/.ssh/known_hosts
      - name: Connect & Execute commands on EC2
        run: | 
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ env.AWS_EC2 }} << EOF
          pwd
          cd ~/P7_Implement_a_scoring_model &&  git pull ${{ env.GITHUB_REPO }}
          pwd
          EOF
      - name: Run unit tests
        run: |
          echo "Run unit tests"
          python ~/P7_Implement_a_scoring_model/tests/unite_test.py
          echo "python tests/ okay"

      - name: Deploy API
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ env.AWS_EC2 }} << EOF
          pwd
          pkill gunicorn || true
          echo "gunicorn killed"

          # cd ~/P7_Implement_a_scoring_model/API/ || exit 1
          # nohup gunicorn --bind 0.0.0.0:5000 app:app

          nohup bash ~/P7_Implement_a_scoring_model/run_API.sh &
          echo "nohup it's okay !"
          EOF
      